import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro',
        'installation',
        // 'quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'core',
        }
      ],
    },
    {
      type: 'category',
      label: 'Integration Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration',
        }
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        }
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        }
      ],
    },
  ],
};

export default sidebars;